version: '3'

services:
  
  web:
    build: web
    ports:
      - "80:3000"
    volumes:
      - ./web:/usr/src/app

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api:/usr/src
